version: '3.4'

services:
  web-test-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  web-test:
    image: web-test
    build:
      context: .
      dockerfile: src/Web/Dockerfile
      target: tests
    depends_on:
      - web-test-sql-server