version: '3.4'

services:
  
  web-sql-server:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5105:80"
